sudo: required
dist: trusty
addons:
  chrome: stable
language: python
python: 
  - "3.6"
branches:
  only:
  - master
install:
  - pip3 install -r Server/requirements.txt
  - pip3 install selenium
  - pip3 install behave
before_script:
  - wget http://chromedriver.storage.googleapis.com/2.23/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6/bin/
  - export CHROME_BIN=chromium-browser
  - python3 Server/app.py &
script:
  - cd Tests
  - behave
