sudo: required
dist: trusty
language: python
python: 
  - "3.6"
install:
  - pip3 install -r Server/requirements.txt
  - pip3 install selenium
  - pip3 install behave
  - pip3 install requests
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
  - tar xvC bin -f geckodriver-v0.20.1-linux64.tar.gz
branches:
  only:
  - master
  - travis-ci
before_script:
  - python3 Server/app.py &
script:
  - cd Tests
  - behave
