language: python
python: 
  - "3.6"
branches:
  only:
  - master
  - travis-ci
install:
  - pip install selenium
  - pip install behave
before_script:
  - wget http://chromedriver.storage.googleapis.com/2.23/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6.3/bin/
  - export CHROME_BIN=chromium-browser
script: behave
