sudo: required
dist: trusty
language: python
addons:
  firefox: "45.4.0esr"
  sauce_connect:
    username: "mckennaman123"
    access_key: "47e14922-2ea6-410c-bee8-8fcecd70045a"
python: 
  - "3.6"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
  - pip3 install -r Server/requirements.txt
  - pip3 install selenium
  - pip3 install behave
  - pip3 install requests
branches:
  only:
  - master
  - travis-ci
before_script:
  - python3 Server/app.py &
script:
  - cd Tests
  - behave
